dataset: "Arabic"

path:
  corpus_path: "C:/Users/btaza/Desktop/hafadhny project/Voice backend Server Python/arabic-speech-corpus" # Corrected path for corpus
  lexicon_path: "C:/Users/btaza/Desktop/hafadhny project/Voice backend Server Python/lexicon/librispeech-lexicon.txt" # Ensure this path is correct
  raw_path: "C:/Users/btaza/Desktop/hafadhny project/Voice backend Server Python/raw_data/Arabic" # Corrected path for raw data
  preprocessed_path: "C:/Users/btaza/Desktop/hafadhny project/Voice backend Server Python/preprocessed_data/Arabic" # Corrected path for preprocessed data
  stats_path: "./" # Keeping as is, or you can provide a full path if needed

preprocessing:
  val_size: 2
  text:
    text_cleaners: []
    language: "ar"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
